[package]
name = "tigr"
version = "0.1.0"
authors = ["Roy Brunton <notnurbyor@googlemail.com>"]
build = "build.rs"
exclude = ["examples/*"]

[build-dependencies]
lalrpop = "*"

[dependencies]
lalrpop-util = "*"
